### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by december-soul** [OFRBG/TsukiBot#10]
Hi

first of all thanks for this great offer.

I'm having some problems starting the bot from the source.
There are a few problems.

I have little idea about nodejs, so please forgive me if I ask stupid questions.

1. common/help. json is missing
2. coins_filtered. json is missing
3. keys. api is missing.

I created the coins_filtered. json and help. json myself.
Unfortunately, I don't know exactly how the keys. api has to look like.
Would it be possible to provide an example keys. api?
I know this file is individual but an example would be helpful.

salutation
DS

**Comment by OFRBG** [comment]
You can get `coins.json` and `coins_filtered.json` if you run the `getCoins.js` file. The keys file looks like

```
{
  "dbots" : [""],
  "infura": [""],
  "polo": [
    "",
    ""
  ],
  "discord": "",
  "etherscan": "",
  "bittrex": [
    "",
    ""
  ],
  "coinbase": [
    "",
    ""
  ],
  "tsukibot": ""
}
```

Of course you need to fill out the fields with your own API keys. If two keys are required, the first field is the public key.

**Comment by december-soul** [comment]
great now it works!

**Comment by december-soul** [comment]
next question.
What about kl_idx.R ?
it is missing

**Comment by OFRBG** [comment]
`kl_index.R` is an R script that I have in a private repository. I'll make that public in the future.
