### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by dgsus** [OFRBG/TsukiBot#7]
hi,

first of all great work!!! i was wondering if you could create a command to enable or disable the commands you have available for the bot, and (most importantly) to be able to assign a role to the users that are allowed to use the commands on the bot.

Thank you in advance!
D

**Comment by OFRBG** [comment]
Thanks for the suggestion. So you mean something like allowing only the use of the kraken price check? And added to that, only certain people with a specific role should be allowed to use the commands?

**Comment by dgsus** [comment]
"So you mean something like allowing only the use of the kraken price check?" yes like a toggle on/off any given command you have. 

"only certain people with a specific role should be allowed to use the commands?" exactly, so the command is not abused by my user base. 

Thank you for considering it!
Daniel

**Comment by OFRBG** [comment]
I've added the first part, which is toggling functions. It's on https://github.com/OFRBG/TsukiBot/commit/98c88b2eecf5a632b7bc097beb12edca27030f0d. You can use it with the command `.tbconfig`.

When I make sure the role-based privileges are working, that command will be available to them as well. Along that one I'll add the general-usage permissions.

**Comment by OFRBG** [comment]
@dgsus I implemented a whole thing around this. Asking for feedback: would you prefer having a fixed name for a role having the permissions, or giving permissions to a existing role?

**Comment by dgsus** [comment]
hi Oscar, awesome!! i think permissions on existing roles would be better =) looking forward to test it
