### ISSUE TITLE
Small Issue + Request

### ISSUE THREAD

**Issue by Infinitay** [OFRBG/TsukiBot#8]
One issue I have noticed is that when I do `.tb p STR BTC` it doesnt give me a reply back. I tried XLM instead of STR as well because they're only still known as STR on Poloniex, and XLM elsewhere.

The request I have is that whenever checking poloniex prices, if the output could be similar as if I was checking the coins price on Bittrex. Currently when checking poloniex prices, you only get the BTC price (or w/e you ask for), but no USD price as well. It's a nice feature for checking prices on bittrex, would love to have it for poloniex as well!

**Comment by OFRBG** [comment]
Thanks for the feedback @Infinitay. I think I can patch this today.

**Comment by OFRBG** [comment]
Reworked Poloniex on 550aced.
