### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by JaneDoe902** [OFRBG/TsukiBot#9]
Is it possible to add Binance Exchange to the available commands ?

thanks

**Comment by OFRBG** [comment]
It is possible. My current issue is actually what to call the command. I ended up using `f` for Bitfinex, but I don't know what would apply for Binance. Bittrex already uses `b`.

**Comment by JaneDoe902** [comment]
would using a B rather than b work?

**Comment by OFRBG** [comment]
Mixing caps is kind of a problem because of mobile users. I finished implementation. The command is currently `n` and works just like Bittrex's. Suggestions for the command name are appreciated.
(e.g. `.tb n tnt gnt btc`)
